### ISSUE TITLE
Environment ambiguity

### ISSUE THREAD

**Issue by jonom** [signify-nz/silverstripe-environmentindicator#1]
Hey, I just noticed this module pop up and overlap with [this SS3 module](https://github.com/jonom/silverstripe-environment-awareness), and just wanted to share a thought on the meaning of environments in SilverStripe. From the docs of that module:

> __Note:__ SilverStripe has a concept of 'environment type' (`SS_ENVIRONMENT_TYPE`) which can be set to 'live', 'test' or 'dev'. This is more like a 'mode' than a type though, because there is nothing to stop you temporarily setting your production environment type to 'dev' to get some debugging information, or your development environment to 'live' to simulate production configuration locally. So you can't really rely on the environment type to know which server environment you're interacting with. `SS_ENVIRONMENT_LABEL` is intended to be a genuine constant, so you can have clarity about which environment you are working on.

In that other module I decided to introduce a `SS_ENVIRONMENT_LABEL` to account for that and also make the naming and number of environments more flexible.

Anyways feel free to delete this, just wanted to point that out :) Nice to see an SS4 solution for this problem in the wild.

**Comment by lanifield** [comment]
Thanks for your feedback Jono. I will definitely look into this and either clarify its use in the documentation or modify the code to account for this ambiguity.

**Comment by lanifield** [comment]
Closing after consultation with team. Functionality out-of-scope for this module.
